apiVersion: v1
kind: PersistentVolume
metadata:
  name: react-build-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "$(pwd)/k8s_path"
    type: Directory

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: react-build-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi