apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ashwin2415/backend:final_gke_v1
          imagePullPolicy: Always
          command:
            - "sh"
            - "-c"
            - |
              python manage.py makemigrations &&
              python manage.py migrate &&
              python manage.py db_load &&
              gunicorn backend.wsgi --bind 0.0.0.0:8000
          ports:
            - containerPort: 8000