apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: songs-worker-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: songs-worker
  minReplicas: 1
  maxReplicas: 5  
  targetCPUUtilizationPercentage: 50